Feature/transaction detail
Alcancia-io/AlcanciaFrontEnd pull request #8
Opened 2022-05-20 19:35 UTC by manu-yaff

Notas:

- El campo de "Comisión" falta en el backend
- Por el momento, se muestra el component en el main-screen. Esto cambiará ya que se tenga la lista de transacciones
- Por ahora se muestra la misma transacción. Esto cambiará ya que se tenga la lista de transacciones
- El font "Gotham" no queda exactamente centrado(verticalmente)

Backend branch: update-transaction-endpoint

2022-05-22 22:41 UTC, AlejandroMinaya commented
Me llama la atención que hay 1900+ files changed. Si vi que se modificaron un buen de SVGs pero no entiendo que lo produjo

2022-05-22 22:41 UTC, AlejandroMinaya commented
> Me llama la atención que hay 1900+ files changed. Si vi que se modificaron un buen de SVGs pero no entiendo que lo produjo

Ya entendí que lo produjo. Es que el target branch es `main` y debería ser `develop`

2022-05-22 22:52 UTC, AlejandroMinaya requested changes

2022-05-22 22:52 UTC, AlejandroMinaya commented on src/app/pages/main-screen/main-screen.page.html
> +										padding-top: 25px;
¿Por qué estos inline styles?

2022-05-22 22:52 UTC, AlejandroMinaya commented on src/app/pages/main-screen/main-screen.page.html
> +										margin-top: 28px;
¿Por qué estos inline styles?

2022-05-22 22:52 UTC, AlejandroMinaya commented on src/app/pages/main-screen/main-screen.page.html
> -                  <div style="width: 100px; float:left; margin:10px; padding-top: 25px;">
¿Por qué estos inline styles?

2022-05-22 22:52 UTC, AlejandroMinaya commented on src/app/app-routing.module.ts
> +  },
Creo que podemos borrar el path, no? Porque la intención no es que el usuario pueda visitar una página donde esté sólo el detalle

2022-05-22 22:52 UTC, AlejandroMinaya commented on src/app/pages/transaction-detail/transaction-detail.page.ts
> +}
Creo que igual podemos borrar este archivo, ya que no sería una página en sí, sino más bien un componente

2022-05-22 22:52 UTC, AlejandroMinaya commented on src/app/services/transaction.service.ts
> +import { Apollo, gql } from 'apollo-angular';
```suggestion
import { Apollo } from 'apollo-angular';
```
Creo que en este archivo ya no está el gql

2022-05-23 21:03 UTC, manu-yaff commented on src/app/pages/main-screen/main-screen.page.html
> +										margin-top: 28px;
Estos inlines ya estaban, en realidad sólo modifique de la línea 1 a la 3, no se porque me los marcó como cambios

2022-05-25 19:19 UTC, merged